/**
 * Map country name -> flag emoji. Handles common variants and
 * composites like "Mexico / USA" by taking the first token.
 * Returns empty string if no mapping is found.
 */
export function countryFlag(country: string | undefined): string {
  if (!country) return "";
  const primary = country.split(/\s*[\/,&]\s*|\s+and\s+/i)[0].trim();
  const key = primary.toLowerCase();
  const map: Record<string, string> = {
    ireland: "🇮🇪",
    usa: "🇺🇸",
    "united states": "🇺🇸",
    america: "🇺🇸",
    ukraine: "🇺🇦",
    spain: "🇪🇸",
    mexico: "🇲🇽",
    méxico: "🇲🇽",
    england: "🇬🇧",
    "united kingdom": "🇬🇧",
    uk: "🇬🇧",
    scotland: "🇬🇧",
    wales: "🇬🇧",
    "northern ireland": "🇬🇧",
    bulgaria: "🇧🇬",
    sweden: "🇸🇪",
    switzerland: "🇨🇭",
    greece: "🇬🇷",
    germany: "🇩🇪",
    nigeria: "🇳🇬",
    lithuania: "🇱🇹",
    slovakia: "🇸🇰",
    france: "🇫🇷",
    italy: "🇮🇹",
    portugal: "🇵🇹",
    poland: "🇵🇱",
    netherlands: "🇳🇱",
    belgium: "🇧🇪",
    austria: "🇦🇹",
    croatia: "🇭🇷",
    serbia: "🇷🇸",
    slovenia: "🇸🇮",
    turkey: "🇹🇷",
    denmark: "🇩🇰",
    norway: "🇳🇴",
    finland: "🇫🇮",
    iceland: "🇮🇸",
    czech: "🇨🇿",
    "czech republic": "🇨🇿",
    hungary: "🇭🇺",
    romania: "🇷🇴",
    israel: "🇮🇱",
    canada: "🇨🇦",
    brazil: "🇧🇷",
    argentina: "🇦🇷",
    australia: "🇦🇺",
    "new zealand": "🇳🇿",
    japan: "🇯🇵",
    china: "🇨🇳",
    "south korea": "🇰🇷",
    korea: "🇰🇷",
    "south africa": "🇿🇦",
    senegal: "🇸🇳",
    cameroon: "🇨🇲",
    congo: "🇨🇩",
    "ivory coast": "🇨🇮",
    "côte d'ivoire": "🇨🇮",
    ghana: "🇬🇭",
    mali: "🇲🇱",
    latvia: "🇱🇻",
    estonia: "🇪🇪",
    georgia: "🇬🇪",
    russia: "🇷🇺",
    belarus: "🇧🇾",
    montenegro: "🇲🇪",
    "north macedonia": "🇲🇰",
    macedonia: "🇲🇰",
    "bosnia and herzegovina": "🇧🇦",
    bosnia: "🇧🇦",
    kosovo: "🇽🇰",
    albania: "🇦🇱",
  };
  return map[key] ?? "";
}
